[package]
name = "rust-wasm"
version = "0.0.1"
edition = "2021"
authors = ["Paul Liferenko <liferenko.it@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"
